### PR TITLE
Support init_existential_value and deinit_existential_value

### PR DESCRIPTION
**Pull request by bryantam**
Issue #91 and Issue #100

### CODE REVIEW

**Review by karimhamdanali — CHANGES_REQUESTED** [review]
Please update the return value to not use `nullptr`.

**Comment by karimhamdanali** [comment]
@bryantam, could you please resolve the conflicts now after merging Mark's PR?

**Comment by bryantam** [comment]
Let me wait until #99 is merged and I will reserve the conflict in one shot.

**Comment by karimhamdanali** [comment]
#99 has now been merged. Please resolve the conflicts on this one here. Thanks @bryantam!

**Review by karimhamdanali — APPROVED** [review]

**Pull request merged**
