### PR TITLE
Added support for ref_to_raw_pointer instruction

### PR DESCRIPTION
**Pull request by mmroz**

### CODE REVIEW

**Review by karimhamdanali — CHANGES_REQUESTED** [review]
LGTM but resolve merge conflicts.

**Review by karimhamdanali — CHANGES_REQUESTED** [review]
Looks like recent merges caused further conflicts. Please resolve.

**Comment by mmroz** [comment]
Resolved

**Review by karimhamdanali — APPROVED** [review]
LGTM

**Pull request merged**
